In [ ]:
import pandas as _hex_pandas
import datetime as _hex_datetime
import json as _hex_json

In [ ]:
hex_scheduled = _hex_json.loads("false")

In [ ]:
hex_user_email = _hex_json.loads("\"example-user@example.com\"")

In [ ]:
hex_user_attributes = _hex_json.loads("{}")

In [ ]:
hex_run_context = _hex_json.loads("\"logic\"")

In [ ]:
hex_timezone = _hex_json.loads("\"UTC\"")

In [ ]:
hex_project_id = _hex_json.loads("\"019ff179-6dfc-725d-a743-c4ca9815e868\"")

In [ ]:
hex_project_name = _hex_json.loads("\"Study Abroad Lead Funnel Analysis\"")

In [ ]:
hex_status = _hex_json.loads("\"\"")

In [ ]:
hex_categories = _hex_json.loads("[]")

In [ ]:
hex_color_palette = _hex_json.loads("[\"#4C78A8\",\"#F58518\",\"#E45756\",\"#72B7B2\",\"#54A24B\",\"#EECA3B\",\"#B279A2\",\"#FF9DA6\",\"#9D755D\",\"#BAB0AC\"]")

### Where are our highest-value customers coming from?

_We'll use _[SQL](https://learn.hex.tech/docs/explore-data/cells/sql-cells/sql-cells-introduction)_ & _[Python](https://learn.hex.tech/docs/explore-data/cells/python-cells)_ to answer this question._

# Problem Statement

```
Mentors' Education's marketing and sales teams need visibility into which lead sources (channels), branches, and counselors are most effective at converting inquiries into enrollments, in order to allocate limited marketing budget and staff resources more efficiently. This analysis examines lead and conversion data across channels, branches, and counselors to identify high- and low-performing segments, uncover bottlenecks in the lead-to-enrollment funnel, and surface actionable, data-driven recommendations that support better resource allocation and process improvement across the organization.

```

# Summary & Key Insights (based on the analysis)

```
Overall Performance
Out of 1,200 leads generated between January 2025 and July 2026, 179 converted into enrollments — an overall conversion rate of 14.9%, while roughly a third of all leads (30.9%) were ultimately lost. This leaves meaningful room for improvement, particularly in how leads are sourced and followed up on.

```
```
Channel Performance
Referral is by far the strongest-performing channel, converting at 30.5% — more than double the next-best channel and nearly three times the rate of Facebook Ads (10.3%), which is also the single largest source of leads by volume (361 leads). This creates a clear volume-versus-quality gap: the channel bringing in the most leads is also the least efficient at converting them. Grouping channels into paid versus organic sources reinforces this pattern — organic channels convert at 18.6% compared to 10.9% for paid channels, suggesting that current ad spend may not be delivering proportionate returns. Reallocating a portion of the Facebook Ads budget toward referral incentive programs or organic lead generation could improve overall efficiency without necessarily increasing total spend.

```
```
Branch Performance
Chattogram leads in conversion rate (16.9%) despite being a mid-sized branch, while Kalabagan — the largest branch by lead volume (431 leads) — converts at a comparatively modest 16.0% and carries the highest lost-lead rate (33.2%). Sylhet, the smallest branch, has both the lowest conversion rate (11.7%) and the fastest average cycle time (29.7 days), indicating a smaller but faster-moving pipeline. These differences suggest branch-level factors — likely counselor capacity, lead quality, or local follow-up practices — are driving performance gaps that warrant closer investigation.

```
```
Counselor Performance
Individual counselor performance varies meaningfully, with conversion rates ranging from 12.0% to 19.8% across the team. Mim and Tanvir stand out as top performers, converting nearly 20% and 18% of their leads respectively, while Rafi and Nusrat trail at around 12%. This spread points to an opportunity for structured knowledge-sharing — understanding what top performers do differently in follow-up cadence or communication could help lift performance across the wider team.

```
```
Demand & Trend Patterns
The UK remains the most sought-after destination (354 leads), followed by Canada and Australia, giving a clear signal for where counselor expertise and marketing content should be concentrated. Monthly trends show noticeable volatility in conversion rate (ranging from roughly 9% to 23% month-to-month) without a strong seasonal pattern, suggesting conversion is currently driven more by lead quality and follow-up execution than by time of year.

```
```
Recommendations

```
1. Shift incremental marketing budget from Facebook Ads toward referral-driving initiatives, given the near 3x gap in conversion efficiency.
2. Investigate Kalabagan's high lost-lead rate despite strong lead volume — likely a follow-up capacity or lead-quality issue rather than a demand issue.
3. Formalize best practices from top-converting counselors (Mim, Tanvir) into training material for the wider counseling team.
4. Continue prioritizing UK, Canada, and Australia-focused resources, given they account for over two-thirds of total demand.

### Data `**Importing**`

In [ ]:
import pandas as pd
raw_data = pd.read_csv('mentors_leads_dataset.csv')
df = raw_data

### Dataset `Analyzing & Wrangling`

In [ ]:
df.shape

(1215, 12)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1215 entries, 0 to 1214
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   lead_id             1215 non-null   object
 1   created_date        1215 non-null   object
 2   branch              1215 non-null   object
 3   channel             1215 non-null   object
 4   country_interested  1215 non-null   object
 5   service_type        1215 non-null   object
 6   counselor           1215 non-null   object
 7   budget_range        1172 non-null   object
 8   follow_up_count     1215 non-null   int64
 9   status              1215 non-null   object
 10  last_update_date    1215 non-null   object
 11  cycle_days          1215 non-null   int64
dtypes: int64(2), object(10)
memory usage: 114.0+ KB

In [ ]:
df.created_date = pd.to_datetime(df.created_date)
df.last_update_date = pd.to_datetime(df.last_update_date)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1215 entries, 0 to 1214
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   lead_id             1215 non-null   object
 1   created_date        1215 non-null   datetime64[ns]
 2   branch              1215 non-null   object
 3   channel             1215 non-null   object
 4   country_interested  1215 non-null   object
 5   service_type        1215 non-null   object
 6   counselor           1215 non-null   object
 7   budget_range        1172 non-null   object
 8   follow_up_count     1215 non-null   int64
 9   status              1215 non-null   object
 10  last_update_date    1215 non-null   datetime64[ns]
 11  cycle_days          1215 non-null   int64
dtypes: datetime64[ns](2), int64(2), object(8)
memory usage: 114.0+ KB

In [ ]:
df.isna().sum()

lead_id                0
created_date           0
branch                 0
channel                0
country_interested     0
service_type           0
counselor              0
budget_range          43
follow_up_count        0
status                 0
last_update_date       0
cycle_days             0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1215 entries, 0 to 1214
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   lead_id             1215 non-null   object
 1   created_date        1215 non-null   datetime64[ns]
 2   branch              1215 non-null   object
 3   channel             1215 non-null   object
 4   country_interested  1215 non-null   object
 5   service_type        1215 non-null   object
 6   counselor           1215 non-null   object
 7   budget_range        1172 non-null   object
 8   follow_up_count     1215 non-null   int64
 9   status              1215 non-null   object
 10  last_update_date    1215 non-null   datetime64[ns]
 11  cycle_days          1215 non-null   int64
dtypes: datetime64[ns](2), int64(2), object(8)
memory usage: 114.0+ KB

In [ ]:
cols = ['lead_id', 'branch', 'channel', 'country_interested', 'service_type', 'counselor', 'status']
for i in cols:
    df[i] = df[i].str.strip().str.title()

In [ ]:
df.lead_id.duplicated().sum()

np.int64(15)

In [ ]:
df.drop_duplicates(subset = 'lead_id', keep = 'first', inplace = True)

In [ ]:
df.lead_id.duplicated().sum()

np.int64(0)

In [ ]:
df.shape

(1200, 12)

In [ ]:
df.lead_id.value_counts()

lead_id
Ld00001    1
Ld00002    1
Ld00003    1
Ld00004    1
Ld00005    1
          ..
Ld01196    1
Ld01197    1
Ld01198    1
Ld01199    1
Ld01200    1
Name: count, Length: 1200, dtype: int64

In [ ]:
df['budget_range'] = df['budget_range'].fillna('Not provided')

In [ ]:
df.isna().sum()

lead_id               0
created_date          0
branch                0
channel               0
country_interested    0
service_type          0
counselor             0
budget_range          0
follow_up_count       0
status                0
last_update_date      0
cycle_days            0
dtype: int64

In [ ]:
df

,lead_id,created_date,branch,channel,country_interested,service_type,counselor,budget_range,follow_up_count,status,last_update_date,cycle_days
0,Ld00001,2025-02-21,Uttara,Website Form,Usa,Study Abroad Consultation,Priya,20+ Lakh,3,Lost,2025-03-04,11
1,Ld00002,2026-06-18,Kalabagan,Referral,Uk,Visa Processing,Nusrat,10-20 Lakh,4,Visa Approved,2026-07-31,100
2,Ld00003,2025-07-31,Kalabagan,Google Ads,Canada,Study Abroad Consultation,Arafat,<5 Lakh,3,Consultation Done,2025-08-01,1
3,Ld00004,2025-06-29,Kalabagan,Walk-In,Uk,Study Abroad Consultation,Priya,10-20 Lakh,5,Enrolled,2025-07-14,15
4,Ld00005,2025-02-15,Dhanmondi,Referral,Australia,Study Abroad Consultation,Priya,<5 Lakh,2,New,2025-03-03,16
...,...,...,...,...,...,...,...,...,...,...,...,...
1195,Ld01196,2025-06-01,Dhanmondi,Seminar/Event,Germany,Study Abroad Consultation,Shuvo,5-10 Lakh,4,Application Submitted,2025-10-26,147
1196,Ld01197,2026-01-07,Kalabagan,Facebook Ads,Uk,Ielts Preparation,Shuvo,5-10 Lakh,2,Consultation Done,2026-01-22,15
1197,Ld01198,2025-07-27,Uttara,Facebook Ads,Uk,Ielts Preparation,Nusrat,5-10 Lakh,1,Consultation Done,2025-08-13,17
1198,Ld01199,2025-06-11,Chattogram,Facebook Ads,Australia,Visa Processing,Arafat,20+ Lakh,3,Lost,2025-07-22,41
1199,Ld01200,2026-07-15,Kalabagan,Referral,Australia,Visa Processing,Shuvo,<5 Lakh,4,Enrolled,2026-07-31,87

#### Outlier `Detection` & `Removal`

In [ ]:
df.describe()

,created_date,follow_up_count,last_update_date,cycle_days
count,1200,1200.000000,1200,1200.000000
mean,2025-10-07 21:34:48,3.000000,2025-11-09 17:14:24,34.676667
min,2025-01-01 00:00:00,0.000000,2025-01-06 00:00:00,0.000000
25%,2025-05-20 00:00:00,2.000000,2025-06-26 00:00:00,10.000000
50%,2025-10-08 00:00:00,3.000000,2025-11-10 00:00:00,18.000000
75%,2026-02-21 06:00:00,4.000000,2026-03-27 12:00:00,48.000000
max,2026-07-30 00:00:00,11.000000,2026-07-31 00:00:00,149.000000
std,NaN,1.707561,NaN,36.348955

In [ ]:
df[df.follow_up_count<0]

In [ ]:
df['cycle_days'] = (df.last_update_date - df.created_date).dt.days
df[df.cycle_days<0]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1200 entries, 0 to 1199
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   lead_id             1200 non-null   object
 1   created_date        1200 non-null   datetime64[ns]
 2   branch              1200 non-null   object
 3   channel             1200 non-null   object
 4   country_interested  1200 non-null   object
 5   service_type        1200 non-null   object
 6   counselor           1200 non-null   object
 7   budget_range        1200 non-null   object
 8   follow_up_count     1200 non-null   int64
 9   status              1200 non-null   object
 10  last_update_date    1200 non-null   datetime64[ns]
 11  cycle_days          1200 non-null   int64
dtypes: datetime64[ns](2), int64(2), object(8)
memory usage: 121.9+ KB

In [ ]:
cols = ['follow_up_count', 'cycle_days']
for i in cols:
    mean = df[i].mean()
    std = df[i].std()
    z_score = (df[i] - mean) / std
    df[f'{i}_z_score'] = z_score
df.head()

,lead_id,created_date,branch,channel,country_interested,service_type,counselor,budget_range,follow_up_count,status,last_update_date,cycle_days,follow_up_count_z_score,cycle_days_z_score
0,Ld00001,2025-02-21,Uttara,Website Form,Usa,Study Abroad Consultation,Priya,20+ Lakh,3,Lost,2025-03-04,11,0.000000,-0.629589
1,Ld00002,2026-06-18,Kalabagan,Referral,Uk,Visa Processing,Nusrat,10-20 Lakh,4,Visa Approved,2026-07-31,43,0.585631,0.293766
2,Ld00003,2025-07-31,Kalabagan,Google Ads,Canada,Study Abroad Consultation,Arafat,<5 Lakh,3,Consultation Done,2025-08-01,1,0.000000,-0.918137
3,Ld00004,2025-06-29,Kalabagan,Walk-In,Uk,Study Abroad Consultation,Priya,10-20 Lakh,5,Enrolled,2025-07-14,15,1.171262,-0.514169
4,Ld00005,2025-02-15,Dhanmondi,Referral,Australia,Study Abroad Consultation,Priya,<5 Lakh,2,New,2025-03-03,16,-0.585631,-0.485314

In [ ]:
outlier_profile = df[(((df['follow_up_count_z_score'] > 3) | (df['follow_up_count_z_score'] > 3)) | ((df['cycle_days_z_score'] > 3) | (df['cycle_days_z_score'] > 3)))]

In [ ]:
outlier_profile

,lead_id,created_date,branch,channel,country_interested,service_type,counselor,budget_range,follow_up_count,status,last_update_date,cycle_days,follow_up_count_z_score,cycle_days_z_score
60,Ld00061,2025-01-05,Sylhet,Walk-In,Canada,Study Abroad Consultation,Mim,5-10 Lakh,7,Enrolled,2025-05-27,142,2.342523,3.150396
86,Ld00087,2025-03-02,Kalabagan,Seminar/Event,Canada,Language Course,Shuvo,5-10 Lakh,0,Enrolled,2025-07-21,141,-1.756892,3.121541
95,Ld00096,2025-02-14,Dhanmondi,Facebook Ads,Uk,Study Abroad Consultation,Nusrat,<5 Lakh,4,Visa Approved,2025-07-10,146,0.585631,3.265815
103,Ld00104,2025-05-19,Kalabagan,Google Ads,Canada,Study Abroad Consultation,Arafat,Not provided,9,Enrolled,2025-07-04,46,3.513785,0.380331
124,Ld00125,2025-08-26,Dhanmondi,Google Ads,Canada,Study Abroad Consultation,Tanvir,<5 Lakh,4,Enrolled,2026-01-19,146,0.585631,3.265815
209,Ld00210,2025-07-23,Kalabagan,Facebook Ads,Germany,Study Abroad Consultation,Priya,20+ Lakh,3,Visa Approved,2025-12-17,147,0.000000,3.294670
245,Ld00246,2025-01-28,Kalabagan,Referral,Usa,Study Abroad Consultation,Rafi,5-10 Lakh,10,Contacted,2025-01-31,3,4.099415,-0.860427
277,Ld00278,2025-12-19,Dhanmondi,Facebook Ads,Usa,Study Abroad Consultation,Mim,10-20 Lakh,1,Enrolled,2026-05-07,139,-1.171262,3.063831
296,Ld00297,2025-07-26,Sylhet,Facebook Ads,Uk,Study Abroad Consultation,Tanvir,10-20 Lakh,4,Enrolled,2025-12-14,141,0.585631,3.121541
305,Ld00306,2025-05-02,Kalabagan,Google Ads,Australia,Language Course,Shuvo,10-20 Lakh,3,Enrolled,2025-09-27,148,0.000000,3.323525
517,Ld00518,2025-07-22,Dhanmondi,Facebook Ads,Usa,Study Abroad Consultation,Nusrat,10-20 Lakh,1,Enrolled,2025-12-15,146,-1.171262,3.265815
524,Ld00525,2026-02-08,Uttara,Walk-In,Canada,Study Abroad Consultation,Rafi,<5 Lakh,2,Enrolled,2026-07-07,149,-0.585631,3.352380
535,Ld00536,2025-04-23,Kalabagan,Referral,Canada,Ielts Preparation,Tanvir,5-10 Lakh,3,Enrolled,2025-09-14,144,0.000000,3.208106
554,Ld00555,2025-02-23,Kalabagan,Google Ads,Uk,Study Abroad Consultation,Arafat,<5 Lakh,6,Application Submitted,2025-07-17,144,1.756892,3.208106
586,Ld00587,2026-07-15,Chattogram,Referral,Uk,Ielts Preparation,Nusrat,20+ Lakh,11,Application Submitted,2026-07-31,16,4.685046,-0.485314
633,Ld00634,2025-02-19,Chattogram,Facebook Ads,Australia,Ielts Preparation,Mim,5-10 Lakh,4,Enrolled,2025-07-13,144,0.585631,3.208106
756,Ld00757,2025-08-28,Dhanmondi,Google Ads,Germany,Ielts Preparation,Mim,10-20 Lakh,4,Visa Approved,2026-01-16,141,0.585631,3.121541
882,Ld00883,2025-12-18,Sylhet,Google Ads,Australia,Study Abroad Consultation,Mim,<5 Lakh,9,New,2025-12-23,5,3.513785,-0.802718
883,Ld00884,2025-01-07,Uttara,Walk-In,Australia,Visa Processing,Arafat,20+ Lakh,3,Enrolled,2025-06-01,145,0.000000,3.236960
886,Ld00887,2026-05-11,Kalabagan,Facebook Ads,Uk,Study Abroad Consultation,Rafi,10-20 Lakh,9,Lost,2026-05-28,17,3.513785,-0.456460
895,Ld00896,2026-02-24,Dhanmondi,Google Ads,Australia,Ielts Preparation,Nusrat,5-10 Lakh,1,Application Submitted,2026-07-17,143,-1.171262,3.179251
1100,Ld01101,2025-11-18,Kalabagan,Referral,Germany,Study Abroad Consultation,Shuvo,10-20 Lakh,4,Enrolled,2026-04-09,142,0.585631,3.150396
1108,Ld01109,2026-03-05,Uttara,Facebook Ads,Uk,Ielts Preparation,Arafat,20+ Lakh,1,Application Submitted,2026-07-22,139,-1.171262,3.063831
1171,Ld01172,2025-12-15,Kalabagan,Seminar/Event,Uk,Study Abroad Consultation,Priya,10-20 Lakh,9,Consultation Done,2025-12-18,3,3.513785,-0.860427
1195,Ld01196,2025-06-01,Dhanmondi,Seminar/Event,Germany,Study Abroad Consultation,Shuvo,5-10 Lakh,4,Application Submitted,2025-10-26,147,0.585631,3.294670

In [ ]:
follow_max = outlier_profile.follow_up_count.max()
follow_min = outlier_profile.follow_up_count.min()
cycle_max = outlier_profile.cycle_days.max()
cycle_min = outlier_profile.cycle_days.min()
print(f"Follow up count: {follow_min} to {follow_max}")
print(f"Cycle days: {cycle_min} to {cycle_max}")

Follow up count: 0 to 11
Cycle days: 3 to 149

### **Comment: **

#### No `outliers` Detected!

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   lead_id                  1200 non-null   object
 1   created_date             1200 non-null   datetime64[ns]
 2   branch                   1200 non-null   object
 3   channel                  1200 non-null   object
 4   country_interested       1200 non-null   object
 5   service_type             1200 non-null   object
 6   counselor                1200 non-null   object
 7   budget_range             1200 non-null   object
 8   follow_up_count          1200 non-null   int64
 9   status                   1200 non-null   object
 10  last_update_date         1200 non-null   datetime64[ns]
 11  cycle_days               1200 non-null   int64
 12  follow_up_count_z_score  1200 non-null   float64
 13  cycle_days_z_score       1200 non-null   float64
dtypes: datetime64[ns](2), float64(2), int64(2), object(8)
memory usage: 140.6+ KB

In [ ]:
df = df.drop(columns=['follow_up_count_z_score', 'cycle_days_z_score'], errors='ignore')
df.head()

,lead_id,created_date,branch,channel,country_interested,service_type,counselor,budget_range,follow_up_count,status,last_update_date,cycle_days
0,Ld00001,2025-02-21,Uttara,Website Form,Usa,Study Abroad Consultation,Priya,20+ Lakh,3,Lost,2025-03-04,11
1,Ld00002,2026-06-18,Kalabagan,Referral,Uk,Visa Processing,Nusrat,10-20 Lakh,4,Visa Approved,2026-07-31,43
2,Ld00003,2025-07-31,Kalabagan,Google Ads,Canada,Study Abroad Consultation,Arafat,<5 Lakh,3,Consultation Done,2025-08-01,1
3,Ld00004,2025-06-29,Kalabagan,Walk-In,Uk,Study Abroad Consultation,Priya,10-20 Lakh,5,Enrolled,2025-07-14,15
4,Ld00005,2025-02-15,Dhanmondi,Referral,Australia,Study Abroad Consultation,Priya,<5 Lakh,2,New,2025-03-03,16

### Feature `Engineering`

In [ ]:
df['month'] = df['created_date'].dt.month_name()
df['year'] = df['created_date'].dt.year
df['quarter'] = df['created_date'].dt.quarter
df['day'] = df['created_date'].dt.day_name()
paid_channels = ['Google Ads', 'Facebook Ads']
df['channel_details'] = df.channel.map(lambda x: 'paid' if x in paid_channels else 'organic')
df

,lead_id,created_date,branch,channel,country_interested,service_type,counselor,budget_range,follow_up_count,status,last_update_date,cycle_days,month,year,quarter,day,channel_details
0,Ld00001,2025-02-21,Uttara,Website Form,Usa,Study Abroad Consultation,Priya,20+ Lakh,3,Lost,2025-03-04,11,February,2025,1,Friday,organic
1,Ld00002,2026-06-18,Kalabagan,Referral,Uk,Visa Processing,Nusrat,10-20 Lakh,4,Visa Approved,2026-07-31,43,June,2026,2,Thursday,organic
2,Ld00003,2025-07-31,Kalabagan,Google Ads,Canada,Study Abroad Consultation,Arafat,<5 Lakh,3,Consultation Done,2025-08-01,1,July,2025,3,Thursday,paid
3,Ld00004,2025-06-29,Kalabagan,Walk-In,Uk,Study Abroad Consultation,Priya,10-20 Lakh,5,Enrolled,2025-07-14,15,June,2025,2,Sunday,organic
4,Ld00005,2025-02-15,Dhanmondi,Referral,Australia,Study Abroad Consultation,Priya,<5 Lakh,2,New,2025-03-03,16,February,2025,1,Saturday,organic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,Ld01196,2025-06-01,Dhanmondi,Seminar/Event,Germany,Study Abroad Consultation,Shuvo,5-10 Lakh,4,Application Submitted,2025-10-26,147,June,2025,2,Sunday,organic
1196,Ld01197,2026-01-07,Kalabagan,Facebook Ads,Uk,Ielts Preparation,Shuvo,5-10 Lakh,2,Consultation Done,2026-01-22,15,January,2026,1,Wednesday,paid
1197,Ld01198,2025-07-27,Uttara,Facebook Ads,Uk,Ielts Preparation,Nusrat,5-10 Lakh,1,Consultation Done,2025-08-13,17,July,2025,3,Sunday,paid
1198,Ld01199,2025-06-11,Chattogram,Facebook Ads,Australia,Visa Processing,Arafat,20+ Lakh,3,Lost,2025-07-22,41,June,2025,2,Wednesday,paid
1199,Ld01200,2026-07-15,Kalabagan,Referral,Australia,Visa Processing,Shuvo,<5 Lakh,4,Enrolled,2026-07-31,16,July,2026,3,Wednesday,organic

### Data `Analyzing`

### `Channel` Performance analysis

#### কোন `channel` থেকে সবচেয়ে বেশি `lead` আসছে?

In [ ]:
# import jinja2
# raw_query = """
#     with total_leads_per_channel as(
#         select channel, count(lead_id) AS total_leads
#         from df
#         GROUP BY channel
#         order by total_leads DESC
#     )
#     select * from total_leads_per_channel
# """
# sql_query = jinja2.Template(raw_query).render(vars())

### Conversion_rate_per_channel

1. কোন ,`**channel**`,-এর ,`**conversion rate**`, সবচেয়ে বেশি? 
2. কোন channel-এ ,`**lead**`, বেশি কিন্তু ,`**conversion**`, কম?

In [ ]:
# import jinja2
# raw_query = """
#     SELECT
#         channel,
#         COUNT(lead_id) AS total_leads,
#         COUNT(CASE WHEN status = 'Enrolled' THEN lead_id END) AS total_enrolled,
#         ROUND(
#             total_enrolled * 100.0
#             / total_leads,
#             2
#         ) AS conversion_rate_pct
#     FROM df
#     GROUP BY channel
#     ORDER BY conversion_rate_pct DESC
# """
# sql_query = jinja2.Template(raw_query).render(vars())

#### Top 3 `Channels`

In [ ]:
# import jinja2
# raw_query = """
#     select
#         channel,
#         count(lead_id) as total_leads,
#         count(case when status = 'Enrolled' then lead_id end) as enrolled,
#         count(case when status = 'Lost' then lead_id end) as lost,
#         count(case when status in ('Enrolled', 'Lost') then lead_id end) as resolved,
#     
#         round(count(case when status = 'Enrolled' then lead_id end) * 100.0
#               / count(lead_id), 1) as conversion_rate_pct,
#     
#         round(count(case when status = 'Enrolled' then lead_id end) * 100.0
#               / count(case when status in ('Enrolled', 'Lost') then lead_id end), 1) as win_rate_pct,
#     
#         round(count(case when status in ('Enrolled', 'Lost') then lead_id end) * 100.0
#               / count(lead_id), 1) as resolution_rate_pct,
#     
#         round(avg(case when status = 'Enrolled' then cycle_days end), 1) as avg_cycle_won,
#         round(avg(case when status = 'Lost' then cycle_days end), 1) as avg_cycle_lost,
#     
#         round(sum(follow_up_count)
#               /count(case when status = 'Enrolled' then lead_id end), 1) as followups_per_enrolment
#     
#     from df
#     group by channel
#     order by win_rate_pct desc
# """
# sql_query = jinja2.Template(raw_query).render(vars())

In [ ]:
# import jinja2
# raw_query = """
#     with z as (
#         select
#             channel,
#             total_leads,
#             win_rate_pct,
#             resolution_rate_pct,
#             followups_per_enrolment,
#             (win_rate_pct - avg(win_rate_pct) over ())
#                 / nullif(stddev_samp(win_rate_pct) over (), 0) as z_win,
#             (resolution_rate_pct - avg(resolution_rate_pct) over ())
#                 / nullif(stddev_samp(resolution_rate_pct) over (), 0) as z_resolution,
#             (followups_per_enrolment - avg(followups_per_enrolment) over ())
#                 / nullif(stddev_samp(followups_per_enrolment) over (), 0) as z_effort
#         from channel_metrics
#     )
#     select
#         channel,
#         total_leads,
#         win_rate_pct,
#         resolution_rate_pct,
#         followups_per_enrolment,
#         round(z_win, 2) as z_win,
#         round(z_resolution, 2) as z_resolution,
#         round(-z_effort, 2) as z_effort_inverted,
#         round(0.5 * z_win + 0.2 * z_resolution - 0.3 * z_effort, 2) as channel_score
#     from z
#     order by channel_score desc
# """
# sql_query = jinja2.Template(raw_query).render(vars())

In [ ]:
# import jinja2
# raw_query = """
#     select channel, channel_score
#     from channel_metric_scored
#     limit 3
# """
# sql_query = jinja2.Template(raw_query).render(vars())

#### `Paid` vs `organic` channel-এ `পার্থক্য`?

In [ ]:
# import jinja2
# raw_query = """
#     select channel_details, 
#     count(lead_id) as total_leads,
#     count(case when status = 'Enrolled' then lead_id end) as total_enrolled,
#     ROUND(
#             total_enrolled * 100.0
#             / total_leads,
#             2
#         ) as conversion_rate_pct
#     from df
#     group by channel_details
#     order by conversion_rate_pct desc
# """
# sql_query = jinja2.Template(raw_query).render(vars())

### `Branch` Performance analysis

কোন branch-এ `lead` বেশি, কোনটায় `conversion` বেশি?

In [ ]:
# import jinja2
# raw_query = """
#     SELECT
#         branch,
#         COUNT(lead_id) AS total_leads,
#         COUNT(CASE WHEN status = 'Enrolled' THEN lead_id END) AS total_enrolled,
#         ROUND(
#             total_enrolled * 100.0
#             / total_leads,
#             2
#         ) AS conversion_rate_pct
#     FROM df
#     GROUP BY branch
#     ORDER BY conversion_rate_pct DESC
# """
# sql_query = jinja2.Template(raw_query).render(vars())

কোন `branch`-এর `Lost` rate বেশি?

In [ ]:
# import jinja2
# raw_query = """
#     select branch,
#         COUNT(lead_id) AS total_leads,
#         count(case when status = 'Lost' then lead_id end) as total_lost_leads,
#         ROUND(
#             total_lost_leads * 100.0
#             / total_leads,
#             2
#         ) AS lost_rate_pct
#         from df
#         group by branch
#         order by lost_rate_pct DESC
# """
# sql_query = jinja2.Template(raw_query).render(vars())

`Branch` অনুযায়ী `average cycle_days`?

In [ ]:
# import jinja2
# raw_query = """
#     select branch,
#         round(avg(cycle_days), 2) as average_cycle_days
#         from df
#         group by branch
#         order by average_cycle_days
# """
# sql_query = jinja2.Template(raw_query).render(vars())

### `Counselor` Performance Analysis

1. কোন counselor সবচেয়ে বেশি enroll করাতে পেরেছে? 
2. কোন counselor-এর average cycle_days সবচেয়ে কম? 
3. Follow-up বেশি করলে conversion বাড়ে কিনা? hint: এটা group by না, এটা correlation/relationship দেখার বিষয়। দুইভাবে করা যায় — (a) follow_up_count-কে bucket/bin-এ ভাগ করো (যেমন 0-2, 3-5, 6+), তারপর প্রতি bucket-এ conversion rate বের করো, অথবা (b) সরাসরি follow_up_count আর "Enrolled কিনা (1/0)" এর মধ্যে correlation coefficient বের করো (pandas-এ .corr())।

In [ ]:
# import jinja2
# raw_query = """
#     with counselors_performance as(
#             select branch, counselor, 
#             count(lead_id) as total_counseling,
#             count(case when status = 'Enrolled' then lead_id end) as total_enrolled,
#             ROUND(
#             total_enrolled * 100.0
#             / total_counseling,
#             2
#         ) as conversion_rate_pct,
#             floor(avg(cycle_days)) as average_cycle_days
#             from df
#             group by branch, counselor
#             order by branch, conversion_rate_pct desc, average_cycle_days asc
#     )
#     select * from counselors_performance
# """
# sql_query = jinja2.Template(raw_query).render(vars())

In [ ]:
# import jinja2
# raw_query = """
#     select
#         branch || ' — ' || counselor as branch_counselor,
#         branch,
#         counselor,
#         total_counseling,
#         total_enrolled,
#         conversion_rate_pct
#     from counselors_performance
#     order by conversion_rate_pct desc
# """
# sql_query = jinja2.Template(raw_query).render(vars())

In [ ]:
# import jinja2
# raw_query = """
#     with ranked as (
#         select
#             branch,
#             counselor,
#             total_counseling,
#             total_enrolled,
#             conversion_rate_pct,
#             row_number() over (partition by branch order by conversion_rate_pct desc) as rank_best,
#             row_number() over (partition by branch order by conversion_rate_pct asc) as rank_worst
#         from counselors_performance
#     )
#     select
#         branch,
#         counselor,
#         branch || ' — ' || counselor as branch_counselor,
#         case when rank_best = 1 then 'Top' else 'Bottom' end as performance_group,
#         total_counseling,
#         total_enrolled,
#         conversion_rate_pct
#     from ranked
#     where rank_best = 1 or rank_worst = 1
#     order by branch, conversion_rate_pct desc
# """
# sql_query = jinja2.Template(raw_query).render(vars())

`Top counselors` based on `branch`

In [ ]:
# import jinja2
# raw_query = """
#     select branch, counselor, conversion_rate_pct
#     from counselors_performance
#     qualify conversion_rate_pct = max(conversion_rate_pct) over (partition by branch)
#     order by conversion_rate_pct desc
# """
# sql_query = jinja2.Template(raw_query).render(vars())

`Bottom counselors` based on `branch`

In [ ]:
# import jinja2
# raw_query = """
#     select branch, counselor, conversion_rate_pct
#     from counselors_performance
#     qualify conversion_rate_pct = min(conversion_rate_pct) over (partition by branch)
#     order by conversion_rate_pct desc
# """
# sql_query = jinja2.Template(raw_query).render(vars())

### `Product/Demand` Insights

কোন দেশের `demand` সবচেয়ে বেশি?

In [ ]:
# import jinja2
# raw_query = """
#     select country_interested, 
#         count(lead_id) as total_leads
#         from df
#         group by country_interested
#         order by total_leads desc
# """
# sql_query = jinja2.Template(raw_query).render(vars())

In [ ]:
df.status.unique()

array(['Lost', 'Visa Approved', 'Consultation Done', 'Enrolled', 'New',
       'Application Submitted', 'Contacted'], dtype=object)

#### country `deep-dive query analysis`

In [ ]:
# import jinja2
# raw_query = """
#         select country_interested,
#         count(lead_id) as total_leads,
#         count(case when status = 'Enrolled' then lead_id end) as total_enrolled,
#         count(case when status = 'Lost' then lead_id end) as total_lost,
#         count(case when status IN ('Visa Approved', 'Consultation Done', 'New',
#            'Application Submitted', 'Contacted') then lead_id end) as total_on_going,
#         ROUND(
#             total_enrolled * 100.0
#             / total_leads,
#             2
#         ) as conversion_rate_pct,
#         ROUND(
#             total_lost * 100.0
#             / total_leads,
#             2
#         ) as lost_rate_pct,
#         floor(avg(case when status = 'Enrolled' then cycle_days end)) as average_cycle_days
#         from df
#         group by country_interested
#         order by conversion_rate_pct desc
# """
# sql_query = jinja2.Template(raw_query).render(vars())

কোন `service` সবচেয়ে জনপ্রিয়?

In [ ]:
# import jinja2
# raw_query = """
#     select service_type, 
#         count(lead_id) as total_leads from df
#         group by service_type
#         order by total_leads desc
# """
# sql_query = jinja2.Template(raw_query).render(vars())

`Budget range` অনুযায়ী `conversion` আলাদা কিনা?

In [ ]:
# import jinja2
# raw_query = """
#     select country_interested, channel, budget_range,
#         count(lead_id) as total_leads,
#         count(case when status = 'Enrolled' then lead_id end) as total_enrolled,
#         count(case when status = 'Lost' then lead_id end) as total_lost,
#         ROUND(
#             total_enrolled * 100.0
#             / total_leads,
#             2
#         ) as conversion_rate_pct,
#         floor(avg(cycle_days)) as average_cycle_days
#         from df
#         group by country_interested, channel, budget_range
#         having total_leads >= 15
#         order by country_interested, total_leads desc
# """
# sql_query = jinja2.Template(raw_query).render(vars())

কোন `country`-তে কোন `service` বেশি লাগে?

In [ ]:
# import jinja2
# raw_query = """
#     select country_interested, service_type, count(lead_id) as total_leads
#     from df
#     group by country_interested, service_type
#     order by country_interested, total_leads desc
# """
# sql_query = jinja2.Template(raw_query).render(vars())

### `Funnel` Analysis

কোন `stage`-এ সবচেয়ে বেশি `drop` হচ্ছে?

In [ ]:
# import jinja2
# raw_query = """
#     select count(case when status = 'New' then lead_id end) total_new_stage_leads,
#      count(case when status = 'Contacted' then lead_id end) total_Contacted_stage_leads,
#      count(case when status = 'Consultation Done' then lead_id end) total_Consultation_Done_stage_leads,
#      count(case when status = 'Application Submitted' then lead_id end) total_Application_Submitted_stage_leads,
#      count(case when status = 'Enrolled' then lead_id end) total_Enrolled_stage_leads,
#      count(case when status = 'Lost' then lead_id end) total_Lost_leads
#     from df
#     
# """
# sql_query = jinja2.Template(raw_query).render(vars())

In [ ]:
dataframe_21

In [ ]:
dataframe_21

In [ ]:
dataframe_21

In [ ]:
dataframe_21

In [ ]:
dataframe_21

In [ ]:
dataframe_21

Overall` funnel conversion rate`?

In [ ]:
# import jinja2
# raw_query = """
#     select count(lead_id) as total_leads,
#     count(case when status = 'Enrolled' then lead_id end) as total_enrolled,
#     count(case when status = 'Lost' then lead_id end) as total_lost,
#     ROUND(
#             total_enrolled * 100.0
#             / total_leads,
#             2
#         ) as funnel_conversion_rate,
#     ROUND(
#             total_lost * 100.0
#             / total_leads,
#             2
#         ) as funnel_lost_rate,
#         round(avg(cycle_days),2) as average_cycle_days
#     from df
# """
# sql_query = jinja2.Template(raw_query).render(vars())

In [ ]:
dataframe_22

In [ ]:
dataframe_22

In [ ]:
dataframe_22

In [ ]:
dataframe_22

In [ ]:
dataframe_22

### `Trend / Time`-based Analysis

1. মাস অনুযায়ী ,`lead trend`,?
2. সময়ের সাথে ,`conversion rate`, বাড়ছে/কমছে?
3. `Cycle_days`, সময়ের সাথে improve হচ্ছে কিনা?

In [ ]:
# import jinja2
# raw_query = """
#     select
#         year,
#         month,
#         count(lead_id) as total_leads,
#         count(case when status = 'Enrolled' then lead_id end) as total_enrolled,
#         round(
#             ((total_enrolled * 100.0)/total_leads),2
#         ) as monthly_conversion_rate,
#         FLOOR(AVG(cycle_days)) AS average_cycle_days
#     from df
#     group by year, month, month(created_date)
#     order by year asc, month(created_date) asc
# """
# sql_query = jinja2.Template(raw_query).render(vars())

#### Branch and Channel based `conversion Analysis`

In [ ]:
# import jinja2
# raw_query = """
#     select  branch, channel, 
#     count(lead_id) as total_leads,
#     count(case when status = 'Enrolled' then lead_id end) as total_enrolled,
#     round(
#         ((total_enrolled*100.0)/total_leads), 2
#     ) as branch_channel_based_conversion_rate
#     from df
#     group by branch, channel
#     order by branch, branch_channel_based_conversion_rate desc
# """
# sql_query = jinja2.Template(raw_query).render(vars())

In [ ]:
# import jinja2
# raw_query = """
#     
# """
# sql_query = jinja2.Template(raw_query).render(vars())

In [ ]:
# import jinja2
# raw_query = """
#     select
#         cast(year as varchar) as year_label,
#         month,
#         month(created_date) as month_num,
#         count(lead_id) as total_leads
#     from df
#     group by year_label, month, month_num
#     order by year_label, month_num
# """
# sql_query = jinja2.Template(raw_query).render(vars())